version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t silversable16/nodejswebapp1:latest .
            docker push silversable16/nodejswebapp1:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

      
